baseURL: "https://deepayansur.github.io/"
languageCode: "en-us"
title: "Deepayan Sur"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
canonifyURLs:  true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true
customMenus:
    - name: "CV"
      Url: "/cv"
Menus:
  main:
    - identifier: Resume
      name: Resume
      title: View My Resume
      url: "https://drive.google.com/file/d/1MpS3aSm_6FeqqkK3bFr5lMdmtCZKizWQ/view?usp=sharing"
      weight: 1
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Deepayan Sur"
  description: Personal Portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" #"light" # dark

  font:
    fontSize: 1.25rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Deepayan Sur" # Brand name for the brand | default is the title variable
    disableSearch: true
    searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true

    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, I am"
    title: "Deepayan Sur  "
    subtitle: "Machine Learning Engineer"
    content: |-
      I am passionate about leveraging data to drive innovation, I specialize in data science and machine learning, crafting impactful solutions for real-world challenges. With expertise in AI, data analysis, and software engineering, I’m dedicated to building data-driven systems that shape the future.

      As a May 2025 graduate from Viterbi School of Engineering, I am actively seeking Data Science and Machine Learning Engineering roles, with additional interest in Software Engineering and Data Analysis.

      I am currently Open to Full-Time Opportunities in 2025.
    image: /images/hero.png
    bottomImage:
      enable: true
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "View My Resume"
      url: "https://drive.google.com/file/d/1MpS3aSm_6FeqqkK3bFr5lMdmtCZKizWQ/view?usp=sharing"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/deepayansur
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/deepayan-sur/
        - icon: fab fa-instagram
          url: https://www.instagram.com/deepayan_sur/
        - icon: fab fa-twitter
          url: https://twitter.com/DeepayanSur
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am a Computer Science Master's student at USC, specializing in Machine Learning, NLP, and AI-driven systems. My expertise lies in building scalable, data-driven solutions, designing predictive models, and developing NLP systems that drive efficiency and automation.

      With experience in large-scale data processing, model deployment, and AI research, I have worked on user behavior analytics frameworks, enterprise NLP solutions, and high-impact research in Retrieval-Augmented Generation (RAG) and logical reasoning models. My work has led to a 70% boost in efficiency for data-driven systems, 30% improvements in AI-driven formula generation, and mentorship for 150+ trainees in data engineering and ML workflows.

      Currently, I am actively working on AI-driven synthesis engines and scalable ML pipelines, refining LLM models for structured reasoning, and leveraging deep learning to enhance interpretability in scene-based AI models.

      I am actively seeking full-time roles in Data Science and Machine Learning Engineering for 2025, bringing expertise in AI, data pipelines, NLP, and large-scale analytics to solve real-world challenges.
    skills:
      enable: true
      title: "🚀 Technologies & Tools I Work With:"
      items:
        - "<b>Programming Languages:</b> Python, SQL, C++, Java"
        - "<b>Machine Learning & AI:</b> Scikit-learn, TensorFlow, PyTorch, JAX, LangChain, Hugging Face"
        - "<b>Data Processing & Engineering:</b> Pandas, NumPy, Spark, MLflow, DuckDB, Apache Airflow"
        - "<b>NLP & Generative AI:</b> Spacy, Transformers, LlamaIndex, LoRA"
        - "<b>Cloud & DevOps:</b> AWS, Docker, Kubernetes, Weights & Biases"
        - "<b>Model Deployment:</b> FastAPI, Flask, Triton Inference Server"
  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Graduate Researcher"
        company: "USC CPS-VIDA Lab"
        companyUrl: "https://cps-vida.github.io/"
        date: "April 2024 – Present"
        featuredLink:
          enable: false
        content: |
          - Developed an AI-driven synthesis engine, improving user interaction through intelligent recommendation methodologies and managing 14+ concurrent distributed software systems using decision trees.
          - Engineered a Retrieval-Augmented Generation (RAG) framework with LangChain, achieving a **30% improvement** in TQTL formula generation accuracy for translating natural language to logical representations.
          - Fine-tuned LLM models via **Transfer Learning** and **RLHF**, boosting TQTL prediction precision by **25%** on complex natural language datasets for scene interpretation.
          - **Accepted two research papers** at ICSE 2025 and VMCAI 2025.

      - job: "Machine Learning Engineer"
        company: "Highradius Technologies"
        companyUrl: "https://www.highradius.com/"
        date: "July 2022 – June 2023"
        featuredLink:
          enable: false
        content: |
          - Designed and developed a **scalable framework for user behavior analysis** on 1.2M+ user patterns, refining recommendation algorithms for Autonomous Collections, improving user efficiency by **70%**.
          - Implemented an **Email Intent Classifier** and **Email Entities Recognition** system using **Spacy and Named Entity Recognition (NER)**, saving **10% of collector bandwidth** daily.
          - Led training sessions for **150+ trainees** and mentored **12 interns**, collaborating cross-functionally to implement data pipelines for downstream ML tasks.

      - job: "Data Science Intern"
        company: "Highradius Technologies"
        companyUrl: "https://www.highradius.com/"
        date: "April 2021 – June 2022"
        featuredLink:
          enable: false
        content: |
          - Engineered an **end-to-end Cash Flow Predictor** for **4+ client accounts**, focusing on data preprocessing, analysis, and time-series forecasting.
          - Automated **Payment Posting Software** across **3+ ERPs**, integrating API-based automation for improved efficiency.

  # Education
  education:
    enable: true
    index: false
    items:
      - title: "Master of Science in Computer Science"
        school:
          name: "University of Southern California"
          url: "https://www.usc.edu/"
        date: "Aug 2023 – May 2025"
        GPA: "3.57 out of 4.0"
        content: |-
          Relevant Coursework:
            - Machine Learning, Natural Language Processing, Deep Learning
            - Advanced Algorithms, Database Management,Robot Learning

      - title: "Bachelor of Technology in Computer Science Engineering"
        school:
          name: "Kalinga Institute of Industrial Technology"
          url: "https://kiit.ac.in/"
        date: "Jun 2018 – May 2022"
        GPA: "9.21 out of 10.0"
        content: |-
          Relevant Coursework:
            - Algorithms, Database Management, Software Engineering
            - Computer Networks, Operating Systems, Automata & Formal Languages


  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
    - title: "Language Detection in Low Resource Code-Switched Text"
      content: "Developed a BiLSTM-based model achieving 96.31% accuracy in Nepali-English detection and 0.81 F1 score in Hindi-English sentiment analysis."
      image: /images/projects/language.jpeg
      featured:
        name: "Project Report"
        link: https://drive.google.com/file/d/1Ad4hatgKvUdJcYCw_5dKjFEcPyPFaVO7/view
      badges:
        - "NLP"
        - "BiLSTM"
        - "FastText"
      # links:
      #   - icon: fab fa-github
      #     url: https://github.com/your-github-repo

    - title: "CaptionCraft: AI-Powered Image Captioning"
      content: "Built an AI-powered captioning system using Computer Vision Transformers and NLP, increasing social media engagement by 17.6%."
      image: /images/projects/captions.png
      featured:
        name: "Project Report"
        link: https://github.com/haorant14/CaptionWizard/blob/main/CaptionWizard_Final_Report.pdf
      badges:
        - "Computer Vision"
        - "Transformers"
        - "CNN"
      links:
        - icon: fab fa-github
          url: https://github.com/haorant14/CaptionWizard/tree/main



  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: deepayan@usc.edu
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/deepayansur
      linkedin: https://www.linkedin.com/in/deepayan-sur/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
